package com.thinkingtop.kaasservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.1
 * 2012-11-19T11:03:44.483+08:00
 * Generated source version: 2.6.1
 * 
 */
@WebService(targetNamespace = "http://www.thinkingtop.com/kaasservice", name = "ExclusiveKeyService")
@XmlSeeAlso({ObjectFactory.class})
public interface ExclusiveKeyService {

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "Test", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.Test")
    @WebMethod(operationName = "Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.TestResponse")
    public java.util.List<java.lang.String> test(
        @WebParam(name = "testString", targetNamespace = "")
        java.lang.String testString
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "GetState", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetState")
    @WebMethod(operationName = "GetState")
    @ResponseWrapper(localName = "GetStateResponse", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetStateResponse")
    public int getState(
        @WebParam(name = "ecommerceName", targetNamespace = "")
        java.lang.String ecommerceName,
        @WebParam(name = "KeyString", targetNamespace = "")
        java.lang.String keyString
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "GetAPIKeyState", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetAPIKeyState")
    @WebMethod(operationName = "GetAPIKeyState")
    @ResponseWrapper(localName = "GetAPIKeyStateResponse", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetAPIKeyStateResponse")
    public java.util.List<java.lang.String> getAPIKeyState(
        @WebParam(name = "ecommerceName", targetNamespace = "")
        java.lang.String ecommerceName,
        @WebParam(name = "KeyString", targetNamespace = "")
        java.lang.String keyString
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "GetAPIKey", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetAPIKey")
    @WebMethod(operationName = "GetAPIKey")
    @ResponseWrapper(localName = "GetAPIKeyResponse", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetAPIKeyResponse")
    public java.lang.String getAPIKey(
        @WebParam(name = "ecommerceName", targetNamespace = "")
        java.lang.String ecommerceName
    );

    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "GetRecommends", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetRecommends")
    @WebMethod(operationName = "GetRecommends")
    @ResponseWrapper(localName = "GetRecommendsResponse", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetRecommendsResponse")
    public java.util.List<java.lang.String> getRecommends(
        @WebParam(name = "ecommerceName", targetNamespace = "")
        java.lang.String ecommerceName,
        @WebParam(name = "KeyString", targetNamespace = "")
        java.lang.String keyString,
        @WebParam(name = "endUser", targetNamespace = "")
        java.lang.String endUser,
        @WebParam(name = "scheme", targetNamespace = "")
        java.lang.String scheme,
        @WebParam(name = "inputItems", targetNamespace = "")
        java.lang.String inputItems,
        @WebParam(name = "outputItemsNum", targetNamespace = "")
        int outputItemsNum,
        @WebParam(name = "outputQuantitye", targetNamespace = "")
        int outputQuantitye
    );
}
