
package com.thinkingtop.kaasservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ExclusiveKeyService", targetNamespace = "http://www.thinkingtop.com/kaasservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExclusiveKeyService {


    /**
     * 
     * @param keyString
     * @param ecommerceName
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "GetAPIKeyState")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "GetAPIKeyState", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetAPIKeyState")
    @ResponseWrapper(localName = "GetAPIKeyStateResponse", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetAPIKeyStateResponse")
    public List<String> getAPIKeyState(
        @WebParam(name = "ecommerceName", targetNamespace = "")
        String ecommerceName,
        @WebParam(name = "KeyString", targetNamespace = "")
        String keyString);

    /**
     * 
     * @param testString
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "Test")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "Test", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.TestResponse")
    public List<String> test(
        @WebParam(name = "testString", targetNamespace = "")
        String testString);

    /**
     * 
     * @param keyString
     * @param ecommerceName
     * @return
     *     returns int
     */
    @WebMethod(operationName = "GetState")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "GetState", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetState")
    @ResponseWrapper(localName = "GetStateResponse", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetStateResponse")
    public int getState(
        @WebParam(name = "ecommerceName", targetNamespace = "")
        String ecommerceName,
        @WebParam(name = "KeyString", targetNamespace = "")
        String keyString);

    /**
     * 
     * @param keyString
     * @param endUser
     * @param ecommerceName
     * @param scheme
     * @param inputItems
     * @param outputItemsNum
     * @param outputQuantitye
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(operationName = "GetRecommends")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "GetRecommends", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetRecommends")
    @ResponseWrapper(localName = "GetRecommendsResponse", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetRecommendsResponse")
    public List<String> getRecommends(
        @WebParam(name = "ecommerceName", targetNamespace = "")
        String ecommerceName,
        @WebParam(name = "KeyString", targetNamespace = "")
        String keyString,
        @WebParam(name = "endUser", targetNamespace = "")
        String endUser,
        @WebParam(name = "scheme", targetNamespace = "")
        String scheme,
        @WebParam(name = "inputItems", targetNamespace = "")
        String inputItems,
        @WebParam(name = "outputItemsNum", targetNamespace = "")
        int outputItemsNum,
        @WebParam(name = "outputQuantitye", targetNamespace = "")
        int outputQuantitye);

    /**
     * 
     * @param ecommerceName
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetAPIKey")
    @WebResult(name = "result", targetNamespace = "")
    @RequestWrapper(localName = "GetAPIKey", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetAPIKey")
    @ResponseWrapper(localName = "GetAPIKeyResponse", targetNamespace = "http://www.thinkingtop.com/kaasservice", className = "com.thinkingtop.kaasservice.GetAPIKeyResponse")
    public String getAPIKey(
        @WebParam(name = "ecommerceName", targetNamespace = "")
        String ecommerceName);

}
